        @include('include/header')
        @include('include/project_sidebar')

        <!-- body content start-->
        <div class="body-content" >
            <?php $project_id = Request::segment(2); ?>
          @include('include/top_bar')

          <div class="loading_data_file" style="display: none;">
               <div class="block">
                   <img src="{{ url('/resources/assets/img/loading.svg') }}" alt="" />
                   <br/><span class="loading-text">Please wait, file is uploading</span>
               </div>
            </div>

            <!-- page head start-->
            <div class="page-head">
                <h3 class="m-b-less project_name" id="project_name_title"></h3><br/>
                <h3 class="m-b-less">Change Order Request (COR)</h3>

            </div>
            <!-- page head end-->

            <!--body wrapper start-->
            <div class="wrapper" style="display: none;">
                <div class="row">
                    <div class="col-lg-12">
                        <section class="panel">
                            <div class="panel-body">
                                <div id="alert_message"></div>
                                    <div class="col-md-12">
                                        <div class="row">
                                                <section class="panel">
                                                    <p>Contractor: ABC Construction, Inc.</p>
                                                    <div class="tab-parent" style="overflow-x:scroll;">
                                                        <table class="table convert-data-table custom-grid data-table m-t-10">

                                                        <tbody>
                                                            <tr>
                                                                <th>COR#</th>
                                                                <td>1</td>
                                                            </tr>
                                                            <tr>
                                                                <th>Generated By</th>
                                                                <td>ABC Construction, Inc.</td>
                                                            </tr>
                                                            <tr>
                                                                <th>Date Sent</th>
                                                                <td>17-jan-2017</td>
                                                            </tr>
                                                            <tr>
                                                                <th>Description</th>
                                                                <td>Remove Existing Concrete Structure T&M</td>
                                                            </tr>
                                                            <tr>
                                                                <th>Approved by CM</th>
                                                                <td>10/xx/15</td>
                                                            </tr>
                                                            <tr>
                                                                <th>Approved by OWNER</th>
                                                                <td>10/xx/15</td>
                                                            </tr>
                                                            <tr>
                                                                <th>$</th>
                                                                <td>$5,321.38</td>
                                                            </tr>
                                                            <tr>
                                                                <th>Days</th>
                                                                <td>2</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                    </div>
                                                </section>




                                            <div class="col-md-12">


                                                 <form role="form" id="update_swppp_form">
                                                    <div class="row">

                                                    <div class="col-md-4 nopadleft">
                                                        <label><strong>Status</strong></label>
                                                        <select class="form-control">
                                                            <option value="active">Activate</option>
                                                            <option value="deactive">Deactivate</option>
                                                        </select>
                                                    </div>

                                                    <div class="form-group col-md-12 nopadleft m-t-40">
                                                        <a href="{{ url('/dashboard/'.$project_id.'/change_order_request') }}" class="btn btn-info sub-btn no-mar">Back</a>
                                                        <button type="submit" class="btn btn-info sub-btn no-mar">Save</button>
                                                        <p class="loading-submit" style="display: none;">Loading<span>.</span><span>.</span><span>.</span></p>
                                                    </div>

                                                    </div>
                                                </form>


                                            </div>

                                        </div><!-- Row Close -->
                                    </div><!-- Col 6 Close -->

                            </div>
                        </section>
                    </div>


                </div>
            </div>
            <!--body wrapper end-->

<!-- Placed js at the end of the document so the pages load faster -->
<script src="{{ url('/resources/assets/js/jquery-1.10.2.min.js?v=1.0') }}"></script>
<script src="{{ url('/resources/assets/dist/api_url.js?v=1.0') }}"></script>
<script src="{{ url('/resources/assets/js/dropzone.js?v=1.0') }}"></script>
<script type="text/javascript">
$("input[name='response_survey']").click(function(){
    if($('input:radio[name=response_survey]:checked').val() == "owner"){
        console.log('owner');
        $('.response_survey_div').show();
        $('.upload_survey_div').show();
    }
    else {
        console.log('contractor');
        $('.response_survey_div').hide();
        $('.upload_survey_div').show();
    }
});
</script>
<script src="{{ url('/resources/assets/dist/survey_review_update.js?v=1.0') }}"></script>

@include('include/footer')
